create table consulta (data date, hora_final time(6), hora_inicial time(6), tempo time(6), id bigint generated by default as identity, paciente_id bigint, primary key (id));
create table paciente (data_nascimento date, id bigint generated by default as identity, cpf varchar(255) unique, nome varchar(255), primary key (id));
alter table if exists consulta add constraint FK1oq22nlbbvpijm5n2t6vqi1is foreign key (paciente_id) references paciente;
